re-organize intro
datajoint/datajoint-docs-original pull request #19
Opened 2018-08-15 21:24 UTC by dimitri-yatsenko

* Re-organize Introduction
* Address issue #13  in intro/FAQs

2018-08-16 13:35 UTC, eywalker requested changes

2018-08-16 13:35 UTC, eywalker commented on contents/index.rst
You should remove the whole entry of `toctree`for `Contribute`.

2018-08-16 17:43 UTC, dimitri-yatsenko commented on contents/index.rst
done

2018-08-16 18:14 UTC, eywalker approved these changes

2018-08-16 18:15 UTC, merged

2018-09-24 19:34 UTC, austin-hilberg commented
Fixes #13