Documentation content additions and revisions for M2
datajoint/datajoint-docs-original pull request #207
Opened 2018-12-18 20:21 UTC by austin-hilberg

2018-12-18 21:17 UTC, dimitri-yatsenko requested changes
This is a partial review.  I will review again.

2018-12-18 21:17 UTC, dimitri-yatsenko commented on contents/computation/02-keysource.rst
> +**Key source** refers to the set of primary keys over which :ref:`autopopulate <auto>` iterates.
```suggestion
**Key source** refers to the set of primary key values over which :ref:`autopopulate <auto>` iterates, calling the ``make`` method at each iteration.
```

2018-12-18 21:17 UTC, dimitri-yatsenko commented on contents/computation/02-keysource.rst
> +Each ``key`` from the key source is used in the table's ``make`` call.
```suggestion
Each ``key`` from the key source is passed to the table's ``make`` call.
```

2018-12-18 21:17 UTC, dimitri-yatsenko commented on contents/concepts/03-Normalization.rst
> +Some design choices that work well in other database systems poorly fit DataJoint's emphasis on entity normalization.
```suggestion
Design choices lacking entity normalization may lead to data inconsistencies (anomalies). 
```

2018-12-18 21:17 UTC, dimitri-yatsenko commented on contents/concepts/03-Normalization.rst
> +Avoid tables with many attributes that are merely different instances of the same data.
```suggestion
Avoid tables with repeated attributes of the same type. 
```

2018-12-18 21:17 UTC, dimitri-yatsenko commented on contents/concepts/03-Normalization.rst
> +Below are several examples of poorly normalized designs and improved alternatives.
```suggestion
Below are several examples of poorly normalized designs and their normalized alternatives.
```

2018-12-18 21:17 UTC, dimitri-yatsenko commented on contents/concepts/03-Normalization.rst
> +Optional attributes
```suggestion
Inapplicable attributes
```

2018-12-18 21:17 UTC, dimitri-yatsenko commented on contents/concepts/03-Normalization.rst
> +Attributes that do not apply to all entities should be moved to another dependent table containing only the appropriate entities.
```suggestion
If some attributes only apply to a subset of entities in the table, that subset probably describes a distinct entity set that belongs in a different table. 
```

2018-12-18 21:17 UTC, dimitri-yatsenko commented on contents/concepts/03-Normalization.rst
> +If the not all entities in ``Protocol`` involve stimulation, then the ``stimulus`` attribute should be located in another table that depends on ``Protocol`` and references its entities as appropriate
```suggestion
If the not all entities in ``Protocol`` involve stimulation, then the ``stimulus`` attribute should be moved to the part table ``Protocol.Stimulus`` that depends on ``Protocol``.
Only protocols that have a stimulus will have an entry in ``Protocol.Stimulus``.
```

2018-12-18 21:17 UTC, dimitri-yatsenko commented on contents/concepts/04-Integrity.rst
> +An example of a many-to-many relationship would be a table of recording modalities and a dependent table of multimodal recording sessions: sessions depend on multiple modalities, and each modality ap
How can a session be dependent on multiple modalities?  A many-to-many relationship requires a separate association table.

2018-12-18 21:17 UTC, dimitri-yatsenko commented on contents/concepts/04-Integrity.rst
> +In a **many-to-one relationship**, each entity in a downstream table may depend on multiple entities from the same upstream table.
Let's add an example declaration + ERD for each of these four examples.

2018-12-18 21:17 UTC, dimitri-yatsenko commented on contents/definition/04-Definition-Syntax.rst
> +Attribute names should be unique across all tables.
```suggestion
Ideally, attribute names should be unique across all tables that are likely to be used in queries together.
```

2018-12-18 21:17 UTC, dimitri-yatsenko commented on contents/definition/04-Definition-Syntax.rst
> +Nullable attributes can be thought of as optional, such as an attribute that may not have a value for every entity.
```suggestion
A nullable attribute may be thought of as potentially inapplicable to a subset of entities, such as the attribute may not have a value at all.
```

2018-12-18 21:27 UTC, austin-hilberg commented on contents/concepts/03-Normalization.rst
> +Avoid tables with many attributes that are merely different instances of the same data.
I like the simplicity of your edit, but I don't think it quite expresses what should be avoided. I would read your suggestion to mean, "Don't use tables with a lot of `float` attributes." What do you think?

2018-12-18 21:32 UTC, austin-hilberg commented on contents/concepts/03-Normalization.rst
> +Optional attributes
Maybe `optional` is the wrong word, but I don't think ` inapplicable` quite does the trick, because it doesn't indicate the reason this design choice is wrong. "Attributes that only apply to some of the entities" doesn't roll off of the tongue well.

2018-12-18 21:50 UTC, austin-hilberg commented on contents/definition/04-Definition-Syntax.rst
> +Nullable attributes can be thought of as optional, such as an attribute that may not have a value for every entity.
I don't find your suggested change very clear. Also I believe `can` is more appropriate here; `may` usually refers to permission rather than ability.

2018-12-19 15:25 UTC, dimitri-yatsenko commented on contents/concepts/03-Normalization.rst
> +Avoid tables with many attributes that are merely different instances of the same data.
```suggestion
Avoid tables with repeated attributes of the same category.
```

2018-12-19 15:35 UTC, dimitri-yatsenko commented on contents/definition/04-Definition-Syntax.rst
> +Nullable attributes can be thought of as optional, such as an attribute that may not have a value for every entity.
The key distinction is between "optional" and "inapplicable".   If an attribute is optional, then it's okay to keep it in the same table.  If the attribute is not applicable to a distinct subset of entities, they should be separated into a their own table.

2018-12-19 15:43 UTC, dimitri-yatsenko commented on contents/definition/04-Definition-Syntax.rst
> +Nullable attributes can be thought of as optional, such as an attribute that may not have a value for every entity.
For example, if students and employees are in the same table, then the attribute salary will only apply to employees but not students.  The attribute e-mail may be optional but applicable to all.

2018-12-19 15:45 UTC, austin-hilberg commented on contents/definition/04-Definition-Syntax.rst
> +Nullable attributes can be thought of as optional, such as an attribute that may not have a value for every entity.
Did you mean to post these comments under this discussion: https://github.com/datajoint/datajoint-docs/pull/207/files#r242705176 ?

The section here is about appropriately nullable attributes.

2018-12-19 16:09 UTC, austin-hilberg commented on contents/concepts/03-Normalization.rst
> +Optional attributes
How about `inconsistently applicable`?

2018-12-19 16:13 UTC, dimitri-yatsenko requested changes

2018-12-19 16:13 UTC, dimitri-yatsenko commented on contents/queries/06-Restriction.rst
> +Restriction by a query or query object is no different from restriction by a table, because queries in DataJoint adhere to :ref:`entity normalization <normalization>` and produce well-defined entity
```suggestion
Restriction by a query object is a generalization of restriction by a table (which is also a query object), because DataJoint queries always produce well-defined entity sets, as described in  :ref:`entity normalization <normalization>`.
```

2018-12-19 16:13 UTC, dimitri-yatsenko commented on contents/definition/04-Definition-Syntax.rst
> +However, nullable attributes should be used deliberately where their inclusion in an entity is meaningful; they should not be used as a shortcut to easy data entry.
```suggestion
Nullable attributes should be used sparingly to indicate optional rather than inapplicable attributes that still apply to all entities in the table.
```

2018-12-19 16:13 UTC, dimitri-yatsenko commented on contents/definition/04-Definition-Syntax.rst
> +Nullable attributes can be thought of as optional, such as an attribute that may not have a value for every entity.
```suggestion
A nullable attribute may be thought of as having an optional value that may be missing yet applicable to all entities in the table.  
If an attribute is inapplicable to some entities in a table, it probably means that the schema should be redesigned to split entities into separate tables where all attributes apply to all entities.
```

2018-12-19 16:13 UTC, dimitri-yatsenko commented on contents/concepts/03-Normalization.rst
> +Optional attributes
"Attributes that do not apply to all entities"

2018-12-19 16:33 UTC, austin-hilberg commented on contents/definition/04-Definition-Syntax.rst
> +Nullable attributes can be thought of as optional, such as an attribute that may not have a value for every entity.
```suggestion
 A nullable attribute can be thought of as applying to all entities in a table but having an optional *value* that may be absent in some entities.
 Nullable attributes should *not* be used to indicate that an attribute is inapplicable to some entities in a table (see :ref:`normalization`).
```

2018-12-19 16:34 UTC, austin-hilberg commented on contents/definition/04-Definition-Syntax.rst
> +Nullable attributes can be thought of as optional, such as an attribute that may not have a value for every entity.
How's about that?

2018-12-19 16:42 UTC, austin-hilberg commented on contents/concepts/03-Normalization.rst
> +Optional attributes
```suggestion
Attributes that do not apply to all entities
```

2018-12-19 18:46 UTC, dimitri-yatsenko approved these changes

2018-12-19 18:48 UTC, merged