v0.12 doc update
datajoint/datajoint-docs-original pull request #219
Opened 2019-09-12 23:22 UTC by ixcat

See also:

https://github.com/datajoint/datajoint-python/pull/658

2019-10-18 22:22 UTC, dimitri-yatsenko requested changes

2019-10-18 22:22 UTC, dimitri-yatsenko commented on contents/admin/5-blob-config.rst
> +6. Each database schema has an auxiliary table named ``~external`` for each configured external store.
```suggestion
6. Each database schema has an auxiliary table named ``~external_<storename>`` for each configured external store.
```

2019-10-18 22:22 UTC, dimitri-yatsenko commented on contents/admin/5-blob-config.rst
> +    Shallow cleanup removes all objects from the external table which are not referenced by user tables.
There is no longer a separate cleanup. Deleting from the external table is also the cleanup.

2019-10-18 22:22 UTC, dimitri-yatsenko commented on contents/admin/5-blob-config.rst
> +      >>> migrate.migrate_dj011_external_blob_storage_to_dj012(db_schema_name)
we should pass the schema object rather than the schema name.

2019-10-18 22:22 UTC, dimitri-yatsenko commented on contents/external/attach.rst
> +        'location': '/data/attach',
This looks like a relative path where is the location should be an absolute path.  We need to use a path that suggests its absolute nature. E.g. "D:\dj-data"  or "/Volumes/.....

2019-10-18 22:45 UTC, ixcat commented on contents/external/attach.rst
> +        'location': '/data/attach',
It starts with a '/', therefore it is not a relative path in unix-land. But, I can see your point that it may be confusing for those less well versed in these things. That said, I am at a mental impasse to suggest an alternative since I philosophically disagree with a) using windows paths b) using non-semantic paths like /media,  /Volumes, etc. Granted, '/data' is close to being non semantic, but it is 'where one puts data', a 'logical operation', as opposed to 'where one mounts volumes', a physical concern. 

Pick your preference and can implement.

2019-10-18 22:51 UTC, ixcat commented on contents/admin/5-blob-config.rst
> +      >>> migrate.migrate_dj011_external_blob_storage_to_dj012(db_schema_name)
right now, this matches PR - can/will adjust according to PR.

2019-10-28 15:40 UTC, dimitri-yatsenko approved these changes

2019-10-29 13:02 UTC, merged