add multi-schema reference notes
datajoint/datajoint-docs-original pull request #3
Opened 2017-11-06 16:43 UTC by ixcat

2017-11-06 16:53 UTC, dimitri-yatsenko requested changes
This is a good start but in present form it will add more confusion than clarify.  This description belongs in a different section and the terminology and concepts need to be cleaned up.

2017-11-06 16:53 UTC, dimitri-yatsenko commented on computation/Multi-schema.rst
> +Partitioning data into different datasets can be a useful means to categorize
This wording is not ready yet.  This does not have to do with computation and should be described elsewhere.  The data are not actually partitioned. I would avoid using that term.  Schemas are just namespaces.  The use of the terms _module_, _schema_, _project_, and _dataset_ are a bit convoluted here and need to be separated more cleanly.

2017-11-06 16:53 UTC, dimitri-yatsenko commented on computation/Multi-schema.rst
> +In python, using multiple schemas within a single script or session is
I would avoid describing the definition of multiple schemas in the same script.  It's an antipattern.  We will recommend defining one schema per module.

2017-11-06 16:53 UTC, dimitri-yatsenko commented on computation/Multi-schema.rst
> +`spawn_missing_classes`, which will define the classes in the current namespace,
spawn_missing_classes defines classes in the name space of it's schema, not in the current namespace.

2017-11-06 16:53 UTC, dimitri-yatsenko commented on computation/Multi-schema.rst
> +running interpreter and return a valid schema object for that module. A usage
`create_virtual_module` does not return a schema object.

2017-12-11 23:00 UTC, ixcat commented on computation/Multi-schema.rst
> +`spawn_missing_classes`, which will define the classes in the current namespace,
We are actually both incorrect - it will create them in whatever context was passed in to the schema constructor as second argument;

my statement here was saying that It creates classes in the namespace that the schema object was created in; aka the 'current namespace of the schema object' which is in contrast to 'create_virtual_module' which will create in a separate (e.g. non-current) namespace. however this is ambiguous in other ways which I won't get into.

there is no "namespace of it's schema" in the case of running interactively (e.g. __name__==__main__), assuming you use "it's schema" to mean 'schema module' (which itself is an undefined term in our docs) for example..

Clarified language should be more correct, but unfortunately more obtuse.

2017-12-11 23:00 UTC, ixcat commented on computation/Multi-schema.rst
> +running interpreter and return a valid schema object for that module. A usage
this has been corrected/clarified.

2017-12-11 23:00 UTC, ixcat commented on computation/Multi-schema.rst
> +Partitioning data into different datasets can be a useful means to categorize
for partitioning: would 'grouping' be more appropriate? was using the general definition of 'partition' as 'separate into parts'

for computation:

I place this here since more of our 'advanced topics' are somewhat here (auto populate, etc), with the thinking the topic also relates to data managment as a subcategory of computation (ostensibly the inclusion of 'Part tables' is not strictly computing related, etc). Perhaps there should be a separate 'data managment' section? or should the overall section be renamed 'advanced' or something else more general but applicable to all? 

w/r/t schema, module, project, dataset: 

some of these we have not standardized as a whole and in others there is internal ambiguity about these things. I attempted to pick the best, most generic choices to resolve this ambiguity, but it is not always possible given we also have ambiguity internally for what we already do use. Perhaps it would be useful to have a discussion to clarify these various terms? Otherwise it might be useful to go point by point here since without further details I'm only converting one best guess into another one, which could be equally incorrect. That said, a discussion would probably be more time productive.

for example:
https://docs.datajoint.io/data-definition/Notes-on-terminology.html

states:

"A DataJoint schema is

    a database on the database server containing tables with data and
    a collection of classes (in MATLAB or Python) associated with the database, one class for each table.

In MATLAB, the collection of classes is organized as a package, i.e. a file folder starting with a +.

In Python, the collection of classes is any set of classes decorated with the appropriate schema object. Very commonly classes for tables in one database are organized as a distinct Python module. Thus, typical DataJoint projects have one module per database. However, this organization is up to the user’s discretion.
"

However:
https://docs.datajoint.io/data-definition/Create-a-schema.html
(which even links to Notes on terminology page)
states:
```
Schemas

On the database server, related tables are grouped into a named collection called database or schema. This allows organizing the data and controlling access by users. Therefore, we need a way of associating DataJoint classes with their schema. This way we may address tables as schema.TableClassName. Before we create any tables, we must create a schema.
```
which contradicts the definition in notes-on-terminology.

indeed the notes on terminology page even states:
```
For example, what is known as a relation in the formal relational model is called a table in SQL. DataJoint closely adheres to the relational data model and the formal relational terminology is appropriate. Hence, at different points we may refer to the same things using different terms. Sometimes we may say “a row in the table” and on other occasions “a tuple in the relation” – meaning the same thing. Please forgive us. Various historical reasons have contributed to this mixture of terminologies and we will probably continue using them interchangeably.
```

so perhaps it might be a good oppoortunity to take some effort to clarify/update some areas where we know there are confusing terms, and terms that have a clear use case in documenting/explaining datajoint concepts?

2017-12-11 23:00 UTC, ixcat commented on computation/Multi-schema.rst
> +In python, using multiple schemas within a single script or session is
Are you saying that despite the statement:

```
This is typically done for data manipulation/processing purposes; Normal use
would usually be via modules as outlined above. 
```
the whole section should be removed? or should it instead be clarified?

I agree this is not the normal case, hence above statement. Could also make this an 'important' note or something like that.

That said, people do need to do bulk/administrative data management between datajoint schemas at times and using multiple schema objects can be a useful means to accomplish this - We have discussed having separate 'data administrator' documentation vs 'end user' documentation - perhaps the overall document might be a good basis to start doing this in light of the comment about this not being strictly computation related?

2018-08-16 21:20 UTC, dimitri-yatsenko commented
I am closing this because this will be addressed in the revamped documentation.

2018-08-16 21:20 UTC, closed without merging