Edit Queries and Restriction. Format and correct throughout.
datajoint/datajoint-docs-original pull request #95
Opened 2018-10-10 20:03 UTC by austin-hilberg

Add description of query preview in Queries. Fixes #83. 
Document query length and boolean functions. Fixes #90. 
Describe special cases in Restriction. Fixes #81. 
Format references throughout documentation.
Correct incidental typos, etc.

2018-10-10 21:13 UTC, dimitri-yatsenko requested changes

2018-10-10 21:13 UTC, dimitri-yatsenko commented on contents/queries/01-Queries.rst
> +The ``count`` function applied to a query object determines the number of entities returned by the query.
Here count is a method.  "Function" usually refers to a stand-alone function.  Also add an example:
```
# number of ephys sessions since the start of 2018.
n = count(ephys.Session & 'session_date >= "2018-01-01"')
```

2018-10-10 21:13 UTC, dimitri-yatsenko commented on contents/queries/01-Queries.rst
> +The ``exists`` function applied to a query object evaluates to ``true`` if the query returns any entities and to ``false`` if the query does not return any entities.
`exists` is a method.  "Function" usually refers to a stand-alone function. 
"... and to `false` if the query result is empty."

2018-10-10 21:13 UTC, dimitri-yatsenko commented on contents/queries/06-Restriction.rst
> +When restricting table ``A`` with another table, written ``A & B``, the two tables must be **join-compatible**.
make join-compatible a link to the section explaining join compatibility.

2018-10-10 21:13 UTC, dimitri-yatsenko commented on contents/queries/06-Restriction.rst
> +    Exclusion with another table.
Exclusion by another table

2018-10-10 21:13 UTC, dimitri-yatsenko commented on contents/queries/06-Restriction.rst
> +Restriction of table ``A`` with another table ``B`` having none of the same attributes as ``A`` will simply return all entities in ``A``.
unless ``B`` is empty.

2018-10-10 21:13 UTC, dimitri-yatsenko commented on contents/queries/06-Restriction.rst
> +Restriction of table ``A`` with another table ``B`` having none of the same attributes as ``A`` will simply return all entities in ``A``.
If ``B`` is empty, then ``A & B`` is empty no matter what.

2018-10-10 21:13 UTC, dimitri-yatsenko commented on contents/queries/06-Restriction.rst
> +Restriction of table ``A`` with another table ``B`` having none of the same attributes as ``A`` will simply return all entities in ``A``.
Conversely, exclusion by a non-empty table with no common attributes returns the empty set unless the argument.  Exclusion by an empty table always returns the original set.

2018-10-10 21:13 UTC, dimitri-yatsenko commented on contents/queries/06-Restriction.rst
> +   Exclusion with an empty table.
Exclusion by ...?

2018-10-10 21:13 UTC, dimitri-yatsenko commented on contents/queries/06-Restriction.rst
> +Restriction by a query or query object is no different from restriction by a table, because queries in DataJoint adhere to :ref:`normalization <normalization>` and produce well-defined entity sets.
adhere to :ref:\`entity normalization \<normalization\>\` ...

2018-10-10 21:13 UTC, dimitri-yatsenko commented on contents/queries/06-Restriction.rst
> +Exclusion by an empty mapping or by a mapping with no matches will return no entities.
add illustrating examples.

2018-10-10 21:13 UTC, dimitri-yatsenko commented on contents/queries/06-Restriction.rst
> +Exclusion of table ``A`` by an empty collection returns all the entities of ``A``.
Provide examples and explain what a collection is.  In Python, a collection may be a list or a tuple.  In MATLAB a collection might be a cell array or a structure array.

2018-10-10 21:13 UTC, dimitri-yatsenko commented on contents/queries/06-Restriction.rst
> +Note that restriction by an empty collection has inverted behavior from restriction by an empty mapping, ``AndList``, or ``Not`` object.
Please reword and illustrate.  The behavior is not really inverted.  Rather it follows logically from the definitions.

2018-10-10 21:13 UTC, dimitri-yatsenko commented on contents/queries/06-Restriction.rst
> +``A & True`` and ``A - False`` are equivalent to ``A``.
add the matlab equivalents.

2018-10-10 21:13 UTC, dimitri-yatsenko commented on contents/queries/06-Restriction.rst
> +The special function ``dj.Not`` represents logical negation, such that ``A & dj.Not(cond)`` is equivalent to ``A \ cond``.
Do we explain somewhere that the datajoint packages is typically aliased as `dj` when imported and that we use this convention throughout?

2018-10-10 21:13 UTC, dimitri-yatsenko commented on contents/queries/06-Restriction.rst
> +Restriction of table ``A`` by an empty ``Not`` object will return all of the entities in ``A``.
Hm, I do not think that Not can be empty.  It can be Not of an empty collection or Not of an empty AndList.

2018-10-10 21:53 UTC, austin-hilberg commented on contents/queries/06-Restriction.rst
> +Exclusion by an empty mapping or by a mapping with no matches will return no entities.
What kind of example is needed here? Just `A & {} = A`?

2018-10-10 21:59 UTC, dimitri-yatsenko commented on contents/queries/06-Restriction.rst
> +Exclusion by an empty mapping or by a mapping with no matches will return no entities.
Here is a good example:
```
Session & {'sesssion_date': "2018-01-01"}
```
will return the unrestricted `Session` because `session_date` is misspelled.

2018-10-11 19:01 UTC, austin-hilberg commented on contents/queries/06-Restriction.rst
> +The special function ``dj.Not`` represents logical negation, such that ``A & dj.Not(cond)`` is equivalent to ``A \ cond``.
I don't think we do. Where should such an explanation go?

2018-10-11 19:34 UTC, dimitri-yatsenko commented on contents/queries/06-Restriction.rst
> +The special function ``dj.Not`` represents logical negation, such that ``A & dj.Not(cond)`` is equivalent to ``A \ cond``.
Also, we use `-` instead of `\` in the practical implementations.

2018-10-11 19:36 UTC, austin-hilberg commented on contents/queries/06-Restriction.rst
> +The special function ``dj.Not`` represents logical negation, such that ``A & dj.Not(cond)`` is equivalent to ``A \ cond``.
Fixing the `\` in the next commit.

2018-10-11 20:05 UTC, austin-hilberg commented on contents/queries/06-Restriction.rst
> +Note that restriction by an empty collection has inverted behavior from restriction by an empty mapping, ``AndList``, or ``Not`` object.
Can you clarify your comment? It seems inverted to me, despite following logically from the definitions. `A & {}` is the same as `A - []`  is what I mean.

2018-10-11 20:18 UTC, dimitri-yatsenko commented on contents/queries/06-Restriction.rst
> +Note that restriction by an empty collection has inverted behavior from restriction by an empty mapping, ``AndList``, or ``Not`` object.
They are not inverted.  They are very different.  I just would not compare them like that because it gives the impression that they are similar and just inverted.  

Definitions: 
An element of an entity set matches a mapping when it lacks attributes that have namesake attributes in the mapping with a different value.  Therefore, an empty mapping is always a match.

An element of an entity set matches a collection when it matches at least one condition in the collection.  Therefore, an empty collection is never a match.

2018-10-15 15:20 UTC, dimitri-yatsenko approved these changes

2018-10-15 15:20 UTC, dimitri-yatsenko commented on contents/queries/06-Restriction.rst
> +Restriction of table ``A`` by ``dj.Not([])`` will return all of the entities in ``A``.
I think this is unnecessarily specific.  You can just say that the an empty collection (Or-List) evaluates to False whereas an empty And-List evaluates to True.  Then everything else follows from that.

2018-10-15 17:27 UTC, dimitri-yatsenko approved these changes

2018-10-15 17:27 UTC, merged